import type { IResourceSchema } from '@/types';

const assetsSchema: IResourceSchema = {
    id: {
        type: 'number',
        label: 'ID',
        readonly: true,
        showInTable: true,
        showInForm: false,
        showInDetail: true,
    },
    name: {
        type: 'string',
        label: 'Name',
        required: true,
        minLength: 2,
        maxLength: 31,
        showInTable: true,
        showInForm: true,
        showInDetail: true,
        placeholder: 'Enter asset name',
    },
    cost: {
        type: 'number',
        label: 'Cost',
        min: 0,
        showInTable: true,
        showInForm: true,
        showInDetail: true,
        placeholder: 'Enter cost',
    },
    assigneeModel: {
        type: 'enum',
        label: 'Assignee Type',
        enumValues: ['common', 'users', 'locations'] as const,
        default: 'common',
        required: true,
        showInTable: true,
        showInForm: true,
        showInCreate: true,
        showInEdit: false,
        showInDetail: true,
    },
    actualAssigneeModel: {
        type: 'enum',
        label: 'Actual Assignee Type',
        enumValues: ['users', 'locations'] as const,
        showInTable: false,
        showInForm: false,
        showInDetail: false,
    },
    assignee: {
        type: 'polymorphicReference',
        label: 'Assigned To',
        modelField: 'assigneeModel',
        displayField: 'name',
        showInTable: true,
        showInForm: true,
        showInCreate: false,
        showInEdit: true,
        showInDetail: true,
    },
};

export default assetsSchema;
